logging:
  level:
    root: DEBUG
    org.apache: INFO

spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            assertingparty:
              metadata-uri: "https://dev-43510665.okta.com/app/exk94qn95xSuWCczc5d7/sso/saml/metadata"
            entityID: "my-sp-entity-id"
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"

#################
#
# Note: in the Okta Settings, "SP Entity ID" and "SP Issuer" need have the same value
#
#################